infection_rate = [2, 2, 2, 3, 3, 4, 4]

# dictionaries to set up the game

difficulty_array = {'Easy': 4, 'Medium': 5, 'Hard': 6}

all_cities = {'red': {'Ho Chi Minh City':['Jakarta', 'Manila', 'Hong Kong', 'Bangkok'], 'Tokyo':
['Osaka', 'Seoul', 'San Francisco'], 'Bangkok':['Kolkata', 'Chennai', 'Jakarta', 'Ho Chi Minh City', 'Hong Kong'], 'Taipei':['Osaka', 'Shanghai', 'Hong Kong', 'Manila'], 'Beijing':['Seoul', 'Shanghai'], 'Sydney':['Los Angeles', 'Jakarta', 'Manila'], 'Jakarta':['Sydney', 'Ho Chi Minh City', 'Bangkok', 'Chennai'], 'Seoul':['Tokyo', 'Shanghai', 'Beijing'], 'Shanghai':['Beijing', 'Seoul', 'Tokyo', 'Taipei', 'Hong Kong'], 'Manila':['Taipei', 'Hong Kong', 'Ho Chi Minh City', 'Sydney', 'San Francisco'], 'Hong Kong':['Shanghai', 'Taipei', 'Manila', 'Ho Chi Minh City','Bangkok', 'Kolkata'], 'Osaka':['Taipei', 'Tokyo']}, 'black': {'Riyadh' :['Karachi', 'Baghdad', 'Cairo'], 'Kolkata':['Hong Kong', 'Bangkok', 'Chennai', 'Delhi'], 'Tehran':['Moscow', 'Delhi','Karachi', 'Baghdad'],'Delhi':['Kolkata', 'Chennai', 'Mumbai', 'Karachi', 'Tehran'], 'Mumbai':['Karachi', 'Delhi', 'Chennai'], 'Baghdad':['Tehran', 'Karachi', 'Riyadh', 'Cairo', 'Istanbul'], 'Karachi':['Mumbai', 'Delhi', 'Tehran', 'Baghdad', 'Riyadh'], 'Algiers':['Madrid', 'Paris', 'Istanbul', 'Cairo'], 'Chennai':['Jakarta', 'Bangkok', 'Kolkata', 'Delhi', 'Mumbai'], 'Istanbul':['St. Petersburg', 'Milan', 'Algiers', 'Cairo', 'Baghdad', 'Moscow'], 'Cairo':['Algiers', 'Istanbul', 'Baghdad', 'Riyadh', 'Khartoum'], 'Moscow':['Tehran', 'Istanbul', 'St. Petersburg']}, 'blue': {'Essen':['St. Petersburg', 'Milan', 'Paris', 'London'], 'St. Petersburg':['Moscow', 'Istanbul', 'Essen'], 'San Francisco':['Tokyo', 'Manila', 'Los Angeles', 'Chicago'], 'Paris':['London', 'Madrid', 'Algiers', 'Essen', 'Milan'], 'Atlanta':['Chicago', 'Miami', 'Washington'], 'London':['New York', 'Madrid', 'Paris', 'Essen'], 'Washington':['Miami', 'Atlanta', 'Montreal', 'New York'], 'Milan':['Essen', 'Paris', 'Istanbul'], 'New York':['Montreal', 'Washington', 'Madrid', 'London'], 'Madrid':['New York', 'London', 'Paris', 'Algiers','Sao Paulo'], 'Montreal':['Chicago', 'Washington', 'New York'], 'Chicago':['San Francisco', 'Los Angeles', 'Mexico City', 'Atlanta', 'Montreal']}, 'yellow': {'Sao Paulo':['Madrid', 'Lagos', 'Buenos Aires', 'Bogota'], 'Johannesburg':['Khartoum', 'Kinshasa'], 'Kinshasa':['Johannesburg', 'Khartoum', 'Lagos'], 'Lagos':['Sao Paulo', 'Kinshasa'], 'Lima':['Santiago', 'Bogota', 'Mexico City'], 'Bogota':['Miami', 'Mexico City', 'Lima', 'Buenos Aires', 'Sao Paulo'], 'Los Angeles':['Mexico City', 'Chicago', 'San Francisco', 'Sydney'], 'Buenos Aires':['Bogota', 'Sao Paulo'], 'Mexico City':['Los Angeles', 'Chicago', 'Miami', 'Bogota', 'Lima'], 'Miami':['Atlanta', 'Washington', 'Bogota', 'Mexico City'], 'Santiago':['Lima'], 'Khartoum':['Cairo', 'Johannesburg', 'Kinshasa', 'Lagos']}}

print(all_cities)